version: "2"

volumes:
    db:

services:
    app:
        build:
            context: .
        privileged: true
        ports:
            - "80:80"

    postgres:
        image: postgres:17-alpine
        environment:
            PGDATA: "/home/postgres/pgdata/data"
        volumes:
            - "db:/home/postgres/pgdata/data"
